#ifndef VERSION_H
#define VERSION_H

#define POWERLAB_APP_NAME   "PowerLab"

#define POWERLAB_APP_VERSION_MAJOR  "0"
#define POWERLAB_APP_VERSION_MINOR  "0"
#define POWERLAB_APP_VERSION_BUILD  "0"

#define POWERLAB_APP_VERSION POWERLAB_APP_VERSION_MAJOR "." POWERLAB_APP_VERSION_MINOR "." POWERLAB_APP_VERSION_BUILD
#endif // VERSION_H
