#ifndef VERSION_H
#define VERSION_H

#define ELECTRONSHIK_PROGRAM_NAME   "Electronshik"

#define ELECTRONSHIK_VERSION_MAJOR  "0"
#define ELECTRONSHIK_VERSION_MINOR  "0"
#define ELECTRONSHIK_VERSION_BUILD  "0"

#define ELECTRONSHIK_VERSION ELECTRONSHIK_VERSION_MAJOR "." ELECTRONSHIK_VERSION_MINOR "." ELECTRONSHIK_VERSION_BUILD
#endif // VERSION_H
