#ifndef MODEL_MESSAGE_H
#define MODEL_MESSAGE_H

#include <string>

namespace Model {
enum class ModelMessage {
  // DEBUG MESSAGES
  DEBUG_META_DATA_PARSING_COMPLETE,
  DEBUG_NEW_MODEL_RESULT_STORAGE,
  DEBUG_NEW_DATA_POINT_FOR_SIGNAL,
  DEBUG_NEW_DATA_FOR_SIGNAL,
  DEBUG_META_DATA_READY,
  DEBUG_NO_FILE_SELECTED,
  DEBUG_DEFAULT_META_DATA_CALLBACK,
  DEBUG_LAST,

  // INFO MESSAGES
  INFO_LAST,

  // WARNING MESSAGES
  WARNING_UNKNOWN_META_DATA,
  WARNING_MAX_SIGNAL_NUMBER_LIMIT,
  WARNING_LAST,

  // ERROR MESSAGES
  ERROR_NO_FILENAME_TO_VALIDATE,
  ERROR_FILE_NOT_OPEN,
  ERROR_ADD_UNKNOWN_TOKEN,
  ERROR_META_DATA_TOKEN_LOAD,
  ERROR_UNEXPECTED_FILE_END,
  ERROR_INVALID_SIGNAL_ID,
  ERROR_META_DATA_NOT_READY,
  ERROR_LAST
};

std::string getMessagePhrase(ModelMessage msg);

} // namespace Model

#endif // MODEL_MESSAGE_H
